pull_request_rules:
  - name: automatic merge for master when reviewed by owner
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - approved-reviews-by=LorenzNickel
      - base=master
    actions:
      merge:
        method: rebase
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix it? 🙏
  - name: automatic merge for Dependabot pull requests with label
    conditions:
      - approved-reviews-by=LorenzNickel
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=continuous-integration/travis-ci/pr
      - "status-success=ci/circleci: test"
    actions:
      merge:
        method: rebase
